development:
  adapter: postgresql
  database: colchonet_dev
  host: localhost
  username: postgres
  password: mj915077
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: colchonet_test
  host: localhost
  username: postgres
  password: mj915077
  pool: 5
  timeout: 5000
